In [1]:
import numpy
import pandas as pd
from sklearn.datasets import fetch_openml

frequency = fetch_openml(
    data_id=41214,
    target_column=None,
    as_frame=True
).frame

severity = fetch_openml(
    data_id=41215,
    target_column=None,
    as_frame=True
).frame

claims = severity.merge(
    frequency,
    on="IDpol",
    how="left",
    validate="many_to_one"
)

In [2]:
claims.head()

,IDpol,ClaimAmount,ClaimNb,Exposure,Area,VehPower,VehAge,DrivAge,BonusMalus,VehBrand,VehGas,Density,Region
0,1552,995.20,2.0,0.59,D,11.0,0.0,39.0,56.0,B12,'Diesel',778.0,R22
1,1010996,1128.12,1.0,0.95,E,4.0,1.0,49.0,50.0,B12,'Regular',2354.0,R11
2,4024277,1851.11,1.0,0.71,D,4.0,2.0,32.0,106.0,B12,'Regular',570.0,R31
3,4007252,1204.00,1.0,0.78,C,4.0,1.0,49.0,57.0,B12,'Regular',288.0,R73
4,4046424,1204.00,1.0,0.86,F,12.0,0.0,37.0,50.0,B12,'Diesel',27000.0,R11

In [ ]:
claims.to_csv('/Users/mukikrishnan/Desktop/Insurance Analytics Platform/data/liability_claims.csv', index=False)

In [5]:
claims.describe()

,IDpol,ClaimAmount,ClaimNb,Exposure,VehPower,VehAge,DrivAge,BonusMalus,Density
count,2.663900e+04,2.663900e+04,26444.000000,26444.000000,26444.000000,26444.000000,26444.000000,26444.000000,26444.000000
mean,2.279864e+06,2.278536e+03,1.139427,0.691791,6.464415,7.355090,45.121502,65.231054,2015.302942
std,1.577202e+06,2.929748e+04,0.617563,0.313213,2.017260,5.165475,14.694677,20.143480,4162.639153
min,1.390000e+02,1.000000e+00,1.000000,0.002740,4.000000,0.000000,18.000000,50.000000,2.000000
25%,1.087642e+06,6.868100e+02,1.000000,0.450000,5.000000,3.000000,34.000000,50.000000,115.000000
50%,2.137413e+06,1.172000e+03,1.000000,0.760000,6.000000,7.000000,45.000000,55.000000,524.500000
75%,3.180162e+06,1.228080e+03,1.000000,1.000000,7.000000,11.000000,54.000000,76.000000,2252.000000
max,6.113971e+06,4.075401e+06,16.000000,2.000000,15.000000,99.000000,99.000000,228.000000,27000.000000